[build-system]
requires = [
    "hatchling >= 1.26",
    "geopandas >= 1.1.2",
    "networkx >= 3.6.1",
    "osmnx >= 2.0.2",
]
build-backend = "hatchling.build"

[project]
name = "net2"
version = "0.0.9"
authors = [
  { name="Michael Dorman", email="dorman@post.bgu.ac.il" },
]
description = "Extends 'networkx' for working with spatial networks"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/michaeldorman/net2/"
Issues = "https://github.com/michaeldorman/net2/issues"
